version: '3.8'

services:
  hyperflow:
    container_name: hyperflow
    build: 
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    expose:
      - "80"
      
  loadbalancer:
    image: nginx
    restart: always
    depends_on:
      - hyperflow
    ports:
      - "80:80"